// demos/vue/geo/src/App.vue
<template>
  <ais-index
    app-id="B1G2GM9NG0"
    api-key="aadef574be1f9252bb48d4ea09b5cfe5"
    index-name="demo_geo"
    :query-parameters="{
      hitsPerPage: 6,
      getRankingInfo: true,
      aroundLatLngViaIP: true,
      typoTolerance: 'min'
    }"
  >
    <main class="search-container">
      <div class="right-panel">
        <div id="map">
          <!-- Uncomment the following widget to add a map -->
          <!-- <geo-map/> -->
        </div>
        <div id="searchbox">
          <!-- Uncomment the following widget to add a search bar -->
          <!-- <ais-search-box placeholder="Search airports by name, city, airport code" class="ais-search-box"/> -->
        </div>
        <div id="stats">
          <!-- Uncomment the following widget to add search stats -->
          <!-- <div>
            <ais-stats>
              <div slot-scope="{ totalResults, processingTime, query, resultStart, resultEnd }">
                ⚡️ <strong>{{ totalResults }}</strong> results found
                <span v-if="query !== ''">for <strong>"{{ query }}"</strong></span>
                in <strong>{{ processingTime }}ms</strong>
              </div>
            </ais-stats>
          </div> -->
        </div>
      </div>
      <div class="left-panel">
        <div id="hits">
          <!-- Uncomment the following widget to add hits list -->
          <!-- <ais-results>
            <template slot-scope="{ result }">
              <hit :result="result"/>
            </template>
          </ais-results>
          <ais-no-results>
            <div slot-scope="props">
              No results found for <strong>{{ props.query }}</strong>.
            </div>
          </ais-no-results> -->
        </div>
      </div>
    </main>
    <footer>
      Source Code on
      <a href="https://github.com/algolia/doc-onboarding">GitHub</a> | Powered by
      <a href="https://www.algolia.com">Algolia</a>
    </footer>
  </ais-index>
</template>

<script>
import Hit from './components/Hit'
import GeoMap from './components/GeoMap'

export default {
  components: { Hit, GeoMap }
}
</script>

<style src="./assets/styles.css"></style>

// demos/react/geo/src/App.js
import React, { Component } from "react";
import { InstantSearch, Configure, SearchBox } from "react-instantsearch-dom";
import Stats from "./Stats";
import GoogleMaps from "./GoogleMaps";
import Content from "./Content";
import "./App.css";

class App extends Component {
  render() {
    return (
      <InstantSearch
        appId="B1G2GM9NG0"
        apiKey="aadef574be1f9252bb48d4ea09b5cfe5"
        indexName="demo_geo"
      >
        <Configure
          hitsPerPage={6}
          getRankingInfo
          aroundLatLngViaIP
          typoTolerance="min"
        />
        <main className="search-container">
          <div className="right-panel">
            <div id="map">
              {/* Uncomment the following widget to add a map */}
              {/* <GoogleMaps /> */}
            </div>
            <div id="searchbox">
              {/* Uncomment the following widget to add a search bar */}
              {/* <SearchBox
                translations={{
                  placeholder: "Search airports by name, city, airport code"
                }}
              /> */}
            </div>
            <div id="stats">
              {/* Uncomment the following widget to add search stats */}
              {/* <Stats /> */}
            </div>
          </div>
          <div className="left-panel">
            <div id="hits">
              {/* Uncomment the following widget to add hits list */}
              {/* <Content /> */}
            </div>
          </div>
        </main>
      </InstantSearch>
    );
  }
}

export default App;
