// demos/vue/geo/src/components/Hit.vue
<template>
  <div class="hit">
    <h2 class="hit-name">
      <span class="hit-airport-name">
        <ais-highlight attribute-name="name" :result="result"/>
        <ais-highlight attribute-name="city" :result="result"/>
      </span>
      <span class="hit-airport-code">
        (<ais-highlight attribute-name="airport_id" :result="result"/>)
      </span>
    </h2>
    <p class="hit-location">
      <ais-highlight attribute-name="country" :result="result"/>
      <span class="hit-distance">({{ getFormattedDistance(result._rankingInfo.matchedGeoLocation.distance) }} km away)</span>
    </p>
  </div>
</template>

<script>
export default {
  props: {
    result: Object
  },
  methods: {
    getFormattedDistance(distance) {
      return parseInt(distance / 1000, 10)
    }
  }
}
</script>

// demos/react/geo/src/Hit.js
import React from 'react';
import PropTypes from 'prop-types';
import { Highlight } from 'react-instantsearch-dom';

const Hit = ({ hit }) => (
  <div className="hit">
    <h2 className="hit-name">
      <span className="hit-airport-name">
        <Highlight attribute="name" hit={hit} />{' '}
        {!hit.displayCity && <Highlight attribute="city" hit={hit} />}{' '}
      </span>
      <span className="hit-airport-code">
        (<Highlight attribute="airport_id" hit={hit} />)
      </span>
    </h2>
    <p className="hit-location">
      <Highlight attribute="country" hit={hit} />{' '}
      <span className="hit-distance">
        ({parseInt(hit._rankingInfo.matchedGeoLocation.distance / 1000, 10)} km
        away)
      </span>
    </p>
  </div>
);

Hit.propTypes = {
  hit: PropTypes.object.isRequired,
};

export default Hit;
