// demos/Angular InstantSearch/saas/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  config = {
    appId: 'B1G2GM9NG0',
    apiKey: 'aadef574be1f9252bb48d4ea09b5cfe5',
    indexName: 'demo_saas',
    searchParameters: {
      hitsPerPage: 4,
      distinct: 3
    }
  };

  groupByType(items: Object[]) {
    const newItems = {};
    items.forEach((item: {type}) => {
      console.log(item.type);
      if (!newItems[item.type]) {
        newItems[item.type] = [item];
      } else {
        newItems[item.type].push(item);
      }
    });
    newItems['isEmpty'] = Object.keys(newItems).length === 0;
    return newItems;
  }
}

<ais-instantsearch [config]="config">
  <main class="search-container">
    <div class="left-panel">
      <ais-panel header="Categories" id="type">
        <ais-refinement-list attribute="type">
        </ais-refinement-list>
      </ais-panel>

    </div>
    <div class="right-panel">
      <ais-search-box placeholder="Search in your CRM" id="searchbox"></ais-search-box>
      <ais-stats id="stats">
        <ng-template let-state="state">
          ⚡️
          <strong>{{state.nbHits}}</strong> results found in
          <strong>{{state.processingTimeMS}}ms</strong>
        </ng-template>
      </ais-stats>
      <ais-hits [transformItems]="groupByType">
        <ng-template let-hits="hits" let-results="results">
          <!-- No results message -->
          <div *ngIf="hits.isEmpty">
            No results found matching
            <strong>{{results.query}}</strong>.
          </div>

          <div class="hit" *ngIf="hits['Contact']">
            <h2>Contacts</h2>
            <div class="table-responsive">
              <table>
                <tbody>
                  <tr>
                    <th>Name</th>
                    <th>Account</th>
                    <th>Email</th>
                  </tr>
                  <tr *ngFor="let hit of hits['Contact']">
                    <td>
                      <ais-highlight attribute="Name" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      <ais-highlight attribute="Account" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      <ais-highlight attribute="Email" [hit]="hit">
                      </ais-highlight>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div class="hit" *ngIf="hits['Opportunity']">
            <h2>Opportunities</h2>
            <div class="table-responsive">
              <table>
                <tbody>
                  <tr>
                    <th>Name</th>
                    <th>Account</th>
                    <th>Owner</th>
                    <th>CloseDate</th>
                    <th>StageName</th>
                    <th>Amount</th>
                  </tr>
                  <tr *ngFor="let hit of hits['Opportunity']">
                    <td>
                      <ais-highlight attribute="Name" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      <ais-highlight attribute="Account" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      <ais-highlight attribute="Owner" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      <ais-highlight attribute="CloseDate" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      <ais-highlight attribute="StageName" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      {{hit.Amount}}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div class="hit" *ngIf="hits['Account']">
            <h2>Accounts</h2>
            <div class="table-responsive">
              <table>
                <tbody>
                  <tr>
                    <th>Name</th>
                    <th>Website</th>
                    <th>Owner</th>
                  </tr>
                  <tr *ngFor="let hit of hits['Account']">
                    <td>
                      <ais-highlight attribute="Name" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      <ais-highlight attribute="Website" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      <ais-highlight attribute="Owner" [hit]="hit">
                      </ais-highlight>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div class="hit" *ngIf="hits['Lead']">
            <h2>Leads</h2>
            <div class="table-responsive">
              <table>
                <tbody>
                  <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Owner</th>
                  </tr>
                  <tr *ngFor="let hit of hits['Lead']">
                    <td>
                      <ais-highlight attribute="Name" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      <ais-highlight attribute="Email" [hit]="hit">
                      </ais-highlight>
                    </td>
                    <td>
                      <ais-highlight attribute="Owner" [hit]="hit">
                      </ais-highlight>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </ng-template>
      </ais-hits>
    </div>
  </main>
</ais-instantsearch>
<footer>Source Code on
  <a href="#">GitHub</a> - Powered by
  <a href="https://www.algolia.com">Algolia</a>
</footer>

// demos/Vue InstantSearch/saas/src/App.vue
<template>
  <ais-index
    app-id="B1G2GM9NG0"
    api-key="aadef574be1f9252bb48d4ea09b5cfe5"
    index-name="demo_saas"
    :query-parameters="{
      distinct: 3
    }"
  >
    <main class="search-container">
      <div class="left-panel">
        <div id="type">
          <refinement-list attribute-name="type" header-title="Categories"/>
        </div>
      </div>
      <div class="right-panel">
        <div id="searchbox">
          <ais-search-box placeholder="Search in your CRM" class="ais-search-box"/>
        </div>
        <div id="stats">
          <div>
            <ais-stats>
              <template slot-scope="{ totalResults, processingTime, query, resultStart, resultEnd }">
                ⚡️ <strong>{{ totalResults }}</strong> results found
                <span v-if="query !== ''">for <strong>"{{ query }}"</strong></span>
                in <strong>{{ processingTime }}ms</strong>
              </template>
            </ais-stats>
          </div>
        </div>
        <div id="hits">
          <table-results attribute-for-distinct="type"/>
          <ais-no-results>
            <template slot-scope="props">
              No results found for <strong>{{ props.query }}</strong>.
            </template>
          </ais-no-results>
        </div>
      </div>
    </main>
    <footer>
      Source Code on <a href="#">GitHub</a> - Powered by <a href="https://www.algolia.com">Algolia</a>
    </footer>
  </ais-index>
</template>

<script>
import RefinementList from './components/RefinementList'
import TableResults from './components/TableResults'

export default {
  components: { RefinementList, TableResults }
}
</script>

<style src="./assets/styles.css"></style>
