// demos/react/media/src/Hit.tsx
import React, { useState } from 'react'
import { Highlight, Snippet } from 'react-instantsearch'
import type { Hit } from 'instantsearch.js'

type HitProps = {
  hit: Hit
}

export function Hit({ hit }: HitProps) {
  const [image, setImage] = useState(hit.image)
  return (
    <div>
      <article>
        <div className="post-img">
          <a href={hit.permalink}>
            <img
              src={image}
              onError={() =>
                setImage('https://fakeimg.pl/400x200?text=Preview&font=noto')
              }
            />
          </a>
        </div>
        <div className="post-content">
          <div className="post-date">{hit.post_date_formatted}</div>
          <h2 className="entry-title">
            <a href={hit.permalink} rel="bookmark">
              <Highlight
                attribute="post_title"
                hit={hit}
                highlightedTagName="em"
              />
            </a>
          </h2>
          <div className="post-excerpt">
            <Snippet attribute="content" hit={hit} />
          </div>
          <div className="entry-meta clear">
            <div className="author-gravatar">
              <img src={hit.author_image_url} width="40" height="40" />
            </div>
            <div className="entry-author-content">
              <div className="author-name">
                <Highlight
                  attribute="author_name"
                  hit={hit}
                  highlightedTagName="em"
                />
              </div>
              <div className="post-meta-info">
                {hit.time_to_read} min read in{' '}
                <Highlight
                  attribute="categories"
                  hit={hit}
                  highlightedTagName="em"
                />
              </div>
            </div>
          </div>
        </div>
      </article>
    </div>
  )
}

// demos/Vue InstantSearch/media/src/components/Hit.vue
<template>
  <div>
    <div class="ais-hits--item">
      <article>
        <div class="post-img">
          <a :href="result.permalink">
            <img :src="result.image">
          </a>
        </div>
        <div class="post-content">
          <div class="post-date">{{ result.post_date_formatted }}</div>
          <h2 class="entry-title">
            <a :href="result.permalink" rel="bookmark">
              <ais-highlight :result="result" attribute-name="post_title"/>
            </a>
          </h2>
          <div class="post-excerpt">
            <ais-snippet :result="result" attribute-name="content"/>
          </div>
          <div class="entry-meta clear">
            <div class="author-gravatar">
              <img :src="result.author_image_url" width="40" height="40">
            </div>
            <div class="entry-author-content">
              <div class="author-name">
                <ais-highlight :result="result" attribute-name="author_name"/>
              </div>
              <div class="post-meta-info">
                {{ result.time_to_read }} min read in
                <span v-html="result._highlightResult.categories[0].value"></span>
              </div>
            </div>
          </div>
        </div>
      </article>
    </div>
    <h2>
      <a :href="result.url">
        {{ result.title }}
      </a>
    </h2>
    <p>{{ result.description }}</p>
  </div>
</template>

<script>
export default {
  props: {
    result: Object
  }
}
</script>
