// demos/Angular InstantSearch/e-commerce/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  config = {
    appId: "B1G2GM9NG0",
    apiKey: "aadef574be1f9252bb48d4ea09b5cfe5",
    indexName: "demo_ecommerce",
    searchParameters: {
      hitsPerPage: 5,
      attributesToSnippet: ["description:24"],
      snippetEllipsisText: " [...]"
    }
  };

  groupByType(items: Object[]) {
    const newItems = {};
    items.forEach((item: { type }) => {
      console.log(item.type);
      if (!newItems[item.type]) {
        newItems[item.type] = [item];
      } else {
        newItems[item.type].push(item);
      }
    });
    newItems["isEmpty"] = Object.keys(newItems).length === 0;
    return newItems;
  }
}

<ais-instantsearch [config]="config">
  <main class="search-container">
    <div class="left-panel">
      <ais-panel header="Categories" id="categories">
        <ais-refinement-list attribute="categories">
        </ais-refinement-list>
      </ais-panel>
      <ais-panel header="Brands" id="brands">
        <ais-refinement-list attribute="brand" searchable="true" searchPlaceholder="Search for other">
        </ais-refinement-list>
      </ais-panel>
      <ais-panel header="Price">
        <ais-range-slider attribute="price" pips="false">
        </ais-range-slider>
      </ais-panel>
    </div>
    <div class="right-panel">
      <ais-search-box placeholder="Search for products" id="searchbox"></ais-search-box>
      <ais-stats id="stats">
        <ng-template let-state="state">
          <div *ngIf="state.nbHits > 0">
            ⚡️
            <strong>{{state.nbHits}}</strong>
            results found
            <span *ngIf="state.query.trim().length > 0">
              for
              <strong>"{{state.query.trim()}}"</strong>
            </span>
            in
            <strong>{{state.processingTimeMS}}ms</strong>
          </div>
        </ng-template>
      </ais-stats>
      <ais-hits>
        <ng-template let-hits="hits" let-results="results">
          <div *ngIf="hits.length === 0">
            No results found for
            <strong>{{results.query}}</strong>.
          </div>
          <div class="ais-hits" *ngFor="let hit of hits">
            <div class="hit">
              <div class="hit-image">
                <img src="{{hit.image}}" />
              </div>
              <div class="hit-content">
                <div>
                  <div class="hit-name">
                    <ais-highlight attribute="name" [hit]="hit">
                    </ais-highlight>
                  </div>
                  <div class="hit-description">
                    <p [innerHTML]="hit._snippetResult.description.value"></p>
                  </div>
                </div>
                <div class="hit-price">${{hit.price}}</div>
              </div>
            </div>
          </div>
        </ng-template>
      </ais-hits>
      <ais-pagination id="pagination"></ais-pagination>
    </div>
  </main>
</ais-instantsearch>
<footer>
  Source Code on
  <a href="https://github.com/algolia/doc-onboarding">GitHub</a> | Powered by
  <a href="https://www.algolia.com">Algolia</a>
</footer>

// demos/vue/ecommerce/src/App.vue
<template>
  <ais-index
    app-id="B1G2GM9NG0"
    api-key="aadef574be1f9252bb48d4ea09b5cfe5"
    index-name="demo_ecommerce"
    :query-parameters="{
      hitsPerPage: 5,
      attributesToSnippet: ['description:24'],
      snippetEllipsisText: ' [...]'
    }"
  >
    <main class="search-container">
      <div class="left-panel">
        <div id="categories">
          <refinement-list attribute-name="categories" header-title="Categories"/>
        </div>
        <div id="brands">
          <refinement-list attribute-name="brand" header-title="Brands"/>
        </div>
      </div>
      <div class="right-panel">
        <div id="searchbox">
          <ais-search-box placeholder="Search for products" class="ais-search-box"/>
        </div>
        <div id="stats">
          <div>
            <ais-stats>
              <template slot-scope="{ totalResults, processingTime, query, resultStart, resultEnd }">
                ⚡️ <strong>{{ totalResults }}</strong> results found
                <span v-if="query !== ''">for <strong>"{{ query }}"</strong></span>
                in <strong>{{ processingTime }}ms</strong>
              </template>
            </ais-stats>
          </div>
        </div>
        <div id="hits">
          <ais-results class="ais-hits">
            <template slot-scope="{ result }">
              <hit :result="result"/>
            </template>
          </ais-results>
          <ais-no-results>
            <template slot-scope="props">
              No results found for <strong>{{ props.query }}</strong>.
            </template>
          </ais-no-results>
        </div>
        <div id="pagination">
          <ais-pagination>
            <template slot="first">«</template>
            <template slot="previous">‹</template>
            <template slot="next">›</template>
            <template slot="last">»</template>
          </ais-pagination>
        </div>
      </div>
    </main>
    <footer>
      Source Code on
      <a href="https://github.com/algolia/doc-onboarding">GitHub</a> | Powered by
      <a href="https://www.algolia.com">Algolia</a>
    </footer>
  </ais-index>
</template>

<script>
import Hit from "./components/Hit";
import RefinementList from "./components/RefinementList";

export default {
  components: { Hit, RefinementList }
};
</script>

<style src="./assets/styles.css"></style>
