// demos/Vue InstantSearch/e-commerce/src/components/Hit.vue
<template>
  <div class="ais-hits--item">
    <div class="hit">
      <div class="hit-image">
        <img :src="result.image"/>
      </div>
      <div class="hit-content">
        <div>
          <div class="hit-name">
            <ais-highlight :result="result" attribute-name="name"/>
          </div>
          <div class="hit-description">
            <ais-snippet :result="result" attribute-name="description"/>
          </div>
        </div>
        <div class="hit-price">${{ result.price }}</div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    result: Object
  }
}
</script>

// demos/react/ecommerce/src/Hit.js
import React from "react";
import PropTypes from "prop-types";
import { Highlight, Snippet } from "react-instantsearch-dom";

export default Hit;

function Hit({ hit }) {
  return (
    <div className="hit">
      <div className="hit-image">
        <img src={hit.image} />
      </div>
      <div className="hit-content">
        <div>
          <div className="hit-name">
            <Highlight attribute="name" hit={hit} tagName="em" />
          </div>
          <div className="hit-description">
            <Snippet attribute="description" hit={hit} />
          </div>
        </div>
        <div className="hit-price">${hit.price}</div>
      </div>
    </div>
  );
}

Hit.propTypes = {
  hit: PropTypes.object.isRequired
};
