// demos/vue/geo/src/App.vue
<template>
  <ais-index
    app-id="B1G2GM9NG0"
    api-key="aadef574be1f9252bb48d4ea09b5cfe5"
    index-name="demo_geo"
    :query-parameters="{
      hitsPerPage: 6,
      getRankingInfo: true,
      aroundLatLngViaIP: true,
      typoTolerance: 'min'
    }"
  >
    <main class="search-container">
      <div class="right-panel">
        <div id="map">
          <!-- Uncomment the following widget to add a map -->
          <!-- <geo-map/> -->
        </div>
        <div id="searchbox">
          <!-- Uncomment the following widget to add a search bar -->
          <!-- <ais-search-box placeholder="Search airports by name, city, airport code" class="ais-search-box"/> -->
        </div>
        <div id="stats">
          <!-- Uncomment the following widget to add search stats -->
          <!-- <div>
            <ais-stats>
              <div slot-scope="{ totalResults, processingTime, query, resultStart, resultEnd }">
                <span role="img" aria-label="emoji">⚡️</span> <strong>{{ totalResults }}</strong> results found
                <span v-if="query !== ''">for <strong>"{{ query }}"</strong></span>
                in <strong>{{ processingTime }}ms</strong>
              </div>
            </ais-stats>
          </div> -->
        </div>
      </div>
      <div class="left-panel">
        <div id="hits">
          <!-- Uncomment the following widget to add hits list -->
          <!-- <ais-results>
            <template slot-scope="{ result }">
              <hit :result="result"/>
            </template>
          </ais-results>
          <ais-no-results>
            <div slot-scope="props">
              No results found for <strong>{{ props.query }}</strong>.
            </div>
          </ais-no-results> -->
        </div>
      </div>
    </main>
    <footer>
      Source Code on
      <a href="https://github.com/algolia/doc-onboarding">GitHub</a> | Powered by
      <a href="https://www.algolia.com">Algolia</a>
    </footer>
  </ais-index>
</template>

<script>
import Hit from './components/Hit'
import GeoMap from './components/GeoMap'

export default {
  components: { Hit, GeoMap }
}
</script>

<style src="./assets/styles.css"></style>

// demos/angular/geo/src/app/app.component.ts
import  { Component } from '@angular/core';
import { BaseWidget, NgAisInstantSearch } from 'angular-instantsearch';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  config = {
    appId: 'B1G2GM9NG0',
    apiKey: 'aadef574be1f9252bb48d4ea09b5cfe5',
    indexName: 'demo_geo',
    searchParameters: {
      hitsPerPage: 6,
      getRankingInfo: true,
      aroundLatLngViaIP: true,
      highlightPreTag: "<em class='highlight'>",
      highlightPostTag: '</em>',
      typoTolerance: 'min',
    },
  };

  roundNumber = number => parseInt(number, 10);
}

<ais-instantsearch [config]="config">
  <main class="search-container">
    <div class="right-panel">
      <div id="map">
        <!-- Uncomment the following widget to add a map -->
        <!-- <ais-geo-hits></ais-geo-hits> -->
      </div>
      <div id="searchbox">
        <!-- Uncomment the following widget to add a search bar -->
        <!-- <ais-search-box placeholder="Search airports by name, city, airport code"></ais-search-box> -->
      </div>
      <div id="stats">
        <!-- Uncomment the following widget to add search stats -->
        <!-- <ais-stats>
          <ng-template let-state="state">
            <div *ngIf="state.nbHits> 0">
              <span role="img" aria-label="emoji">⚡️</span>
              <strong>{{state.nbHits}}</strong>
              results found
              <span *ngIf="state.query.trim().length > 0">
                for
                <strong>"{{state.query.trim()}}"</strong>
              </span>
              in
              <strong>{{state.processingTimeMS}}ms</strong>
            </div>
          </ng-template>
        </ais-stats> -->
      </div>
    </div>
    <div class="left-panel">
      <div id="hits">
        <!-- Uncomment the following widget to add hits list -->
        <!-- <ais-hits class="ais-Hits">
          <ng-template let-hits="hits" let-results="results">
            <div *ngIf="hits.length === 0">
              No results found matching
              <strong>{{results.query}}</strong>.
            </div>
            <div class="ais-Hits-list">
              <div class="ais-Hits-item" *ngFor="let hit of hits">
                <div class="hit">
                  <h2 class="hit-name">
                    <span ngPreserveWhitespaces class="hit-airport-name">
                      <span [innerHTML]="hit._highlightResult.name.value"></span>
                      <span [innerHTML]="hit._highlightResult.city.value"></span>
                    </span>
                    <span class="hit-airport-code" [innerHTML]="betweenParentheses(hit._highlightResult.airport_id.value)"></span>
                  </h2>
                  <p ngPreserveWhitespaces class="hit-location">
                    <span [innerHTML]="hit._highlightResult.country.value"></span>
                    <span class="hit-distance">
                      <span [innerHTML]="betweenParentheses(roundNumber(hit._rankingInfo.matchedGeoLocation.distance / 1000) + ' km away')"></span>
                    </span>
                  </p>
                </div>
              </div>
            </div>
          </ng-template>
        </ais-hits> -->
      </div>
    </div>
  </main>
</ais-instantsearch>
<footer>
  Source Code on
  <a href="https://github.com/algolia/doc-onboarding">GitHub</a> | Powered by
  <a href="https://www.algolia.com">Algolia</a>
</footer>
