// demos/Angular InstantSearch/media/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  config = {
    appId: 'B1G2GM9NG0',
    apiKey: 'aadef574be1f9252bb48d4ea09b5cfe5',
    indexName: 'demo_media',
    searchParameters: {
      hitsPerPage: 3,
      attributesToSnippet: ["content:14"],
      snippetEllipsisText: " [...]",
      highlightPreTag: "<em class='highlight'>",
      highlightPostTag: "</em>"
    },
  };
}

<ais-instantsearch [config]="config">
  <main class="search-container">
    <div class="left-panel">
      <div id="categories">
        <ais-panel header="Categories" id="type">
          <ais-refinement-list attribute="categories" autoHideContainer="false"></ais-refinement-list>
        </ais-panel>
      </div>
    </div>

    <div class="right-panel">
      <ais-search-box placeholder="Search articles" id="searchbox"></ais-search-box>

      <ais-stats id="stats">
        <ng-template let-state="state">
          ⚡️
          <strong>{{state.nbHits}}</strong>
          results found

          <span *ngIf="state.query.trim().length > 0">
            for
            <strong>"{{state.query.trim()}}"</strong>
          </span>

          in
          <strong>{{state.processingTimeMS}}ms</strong>
        </ng-template>
      </ais-stats>

      <ais-hits id="hits" class="ais-Hits">
        <ng-template let-hits="hits" let-results="results">
          <div *ngIf="hits.length === 0">
            No results found matching
            <strong>{{results.query}}</strong>.
          </div>

          <div class="ais-Hits-list">
            <div class="ais-Hits-item" *ngFor="let hit of hits">
              <article>
                <div class="post-img">
                  <a [href]="hit.permalink">
                    <img [src]="hit.image">
                  </a>
                </div>
                <div class="post-content">
                  <div class="post-date">
                    {{hit.post_date_formatted}}
                  </div>
                  <h2 class="entry-title">
                    <a [href]="hit.permalink" rel="bookmark">
                      {{hit._highlightResult.post_title.value}}
                    </a>
                  </h2>
                  <div class="post-excerpt">
                    {{hit._snippetResult.content.value}}
                  </div>
                  <div class="entry-meta clear">
                    <div class="author-gravatar">
                      <img [src]="hit.author_image_url" width="40" height="40">
                    </div>
                    <div class="entry-author-content">
                      <div class="author-name">
                        {{hit._highlightResult.author_name.value}}
                      </div>
                      <div class="post-meta-info">
                        {{hit.time_to_read}} min read in {{hit._highlightResult.categories[0].value}}
                      </div>
                    </div>
                  </div>
                </div>
              </article>
            </div>
          </div>
        </ng-template>
      </ais-hits>
    </div>
  </main>

  <ais-pagination id="pagination"></ais-pagination>
</ais-instantsearch>

<footer>
  Source Code on
  <a href="#">
    GitHub
  </a>
</footer>

// demos/Vue InstantSearch/media/src/App.vue
<template>
  <ais-index
    app-id="B1G2GM9NG0"
    api-key="aadef574be1f9252bb48d4ea09b5cfe5"
    index-name="demo_media"
    :query-parameters="{
      hitsPerPage: 3,
      attributesToSnippet: ['content:14'],
      snippetEllipsisText: ' [...]'
    }"
  >
    <main class="search-container">
      <div class="left-panel">
        <div id="categories">
          <refinement-list attribute-name="categories" header-title="Categories"/>
        </div>
      </div>
      <div class="right-panel">
        <div id="searchbox">
          <ais-search-box placeholder="Search articles" class="ais-search-box"/>
        </div>
        <div id="stats">
          <div>
            <ais-stats>
              <template slot-scope="{ totalResults, processingTime, query, resultStart, resultEnd }">
                ⚡️ <strong>{{ totalResults }}</strong> results found
                <span v-if="query !== ''">for <strong>"{{ query }}"</strong></span>
                in <strong>{{ processingTime }}ms</strong>
              </template>
            </ais-stats>
          </div>
        </div>
        <div id="hits">
          <ais-results class="ais-hits">
            <template slot-scope="{ result }">
              <hit :result="result"/>
            </template>
          </ais-results>
          <ais-no-results>
            <template slot-scope="props">
              No results found for <strong>{{ props.query }}</strong>.
            </template>
          </ais-no-results>
        </div>
        <div id="pagination">
          <ais-pagination>
            <template slot="first">«</template>
            <template slot="previous">‹</template>
            <template slot="next">›</template>
            <template slot="last">»</template>
          </ais-pagination>
        </div>
      </div>
    </main>
    <footer>Source Code on <a href="#">GitHub</a></footer>
  </ais-index>
</template>

<script>
import Hit from './components/Hit'
import RefinementList from './components/RefinementList'

export default {
  components: { Hit, RefinementList }
}
</script>

<style src="./assets/styles.css"></style>
